Vagrant.configure("2") do |config|
  workerNode=2
  # Worker server
  (1..workerNode).each do |i|
    config.vm.define "kworker#{i}" do |kworker|
      kworker.vm.box = "debian/stretch64"
      kworker.vm.hostname = "kworker#{i}"
      kworker.vm.network "private_network", ip: "192.168.33.1#{i}"
      kworker.vm.provider "virtualbox" do |vb|
        vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
        vb.name = "vagrant-kworker#{i}"
        vb.memory = 1024
        vb.cpus = 1
      end
      config.vm.provision "shell", inline: <<-SHELL
      sed -i 's/ChallengeResponseAuthentication no/ChallengeResponseAuthentication yes/g' /etc/ssh/sshd_config
#    sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
      service ssh restart
      SHELL
    end
  end
end
