Vagrant.configure("2") do |config|
  etcHosts = ""
  ingressNginx = ""
  wordpress = ""
  wordpressUrl = ""

  # Ask only questions only for up or provision
  case ARGV[0]
    when "provision", "up"
      print "Do you want nginx as ingress controller (y/n) ?\n"
      ingressNginx = STDIN.gets.chomp
      print "\n"

      if ingressNginx == "y"
        print "Do you want a wordpress in you kubernetes cluster (y/n) ?\n"
        wordpress =  STDIN.gets.chomp
        print "\n"

        if wordpress == "y"
          print "Which url for your website ?\n"
          wordpressUrl =  STDIN.gets.chomp
          unless wordpressUrl.empty? then wordpressUrl else 'wordpress.kub' end
        end
      end
    else
      # nothing
  end


  # Nodes
  NODES = [
    { :hostname => "k8s-haproxy", :ip => "10.1.33.20", :cpus => 1, :memory => 512, :type =>"haproxy" },
    { :hostname => "k8s-master1", :ip => "10.1.33.21", :cpus => 2, :memory => 2048, :type =>"node" },
    { :hostname => "k8s-master2", :ip => "10.1.33.22", :cpus => 1, :memory => 2048, :type =>"node" },
    { :hostname => "k8s-worker1", :ip => "10.1.33.31", :cpus => 1, :memory => 1024, :type =>"node" },
    #{ :hostname => "k8s-worker2", :ip => "10.1.33.32", :cpus => 1, :memory => 1024, :type =>"node" },
    { :hostname => "deploy", :ip => "10.1.33.11", :cpus => 1, :memory => 1024, :type =>"deploy" }
  ]

  NODES.each do |node|
    if node[:type] != "haproxy"
      etcHosts += "echo '" + node[:ip] + "  " + node[:hostname] + "' >> /etc/hosts" + "\n"
    else
      etcHosts += "echo '" + node[:ip] + "  " + node[:hostname] + " autoelb.kub ' >> /etc/hosts" + "\n"
    end
  end # node

  config.vm.box = "ubuntu/impish64"
  config.vm.box_url = "ubuntu/impish64"

  NODES.each do |node|
    config.vm.define node[:hostname] do |cfg|
      cfg.vm.hostname = node[:hostname]
      cfg.vm.network "private_network", ip: node[:ip]
      cfg.vm.provider "virtualbox" do |vb|
        # Accelerate the building of VM
        vb.name = "Vagrant-" + node[:hostname]
        vb.cpus = node[:cpus]
        vb.memory = node[:memory]
        vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
        vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
      end # vb
      cfg.vm.provision :shell, :inline => etcHosts
      # update and upgrade VM
      cfg.vm.provision :shell, :path => "update-vm.sh"

      # Only for haproxy
      if node[:type] == "haproxy"
        cfg.vm.provision :shell, :path => "haproxy-install.sh"
      end

      # For all kubernetes nodes
      if node[:type] == "node"
        cfg.vm.provision :shell, :path => "node-install.sh"
      end

      # for deploy server
      if node[:type] == "deploy"
        cfg.vm.provision :shell, :path => "node-install.sh"
        cfg.vm.provision :shell, :path => "deploy-install.sh", :args => ingressNginx
        if wordpress == "y"
          cfg.vm.provision :shell, :path => "nfs-install.sh"
          cfg.vm.provision :shell, :path => "wordpress-install.sh", :args => wordpressUrl
        end
      end
    end # cfg
  end # node
end
